# -*- coding: utf-8 -*-
"""aula1_dataia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFi1pfyjyhL7hoDZAGn1jxgd4yDJF5mx

### 1. Montar o Google Drive
Primeiro, você precisa montar o seu Google Drive para que o Colab possa acessá-lo. Execute a célula abaixo e siga as instruções para autenticar sua conta.
"""

from google.colab import drive
drive.mount('/content/drive')

import plotly.io as pio

# Salva uma versão estática compatível com GitHub sem depender do Kaleido
pio.renderers.default = "svg"

import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio  # 👈 1. Importe o plotly.io

# 👈 2. Adicione esta linha exata:
pio.renderers.default = "colab+png"

!pip install -U "kaleido==0.2.1"

"""### 2. Carregar o arquivo CSV
Depois que seu Drive estiver montado, você pode especificar o caminho para o seu arquivo CSV e carregá-lo em um DataFrame do pandas. Lembre-se de substituir `'caminho/para/seu/arquivo.csv'` pelo caminho real do seu arquivo no Google Drive.
"""

import pandas as pd

# Leitura direta em uma linha
meus_dados = pd.read_csv('/content/drive/MyDrive/dataia/dc_onboarding.csv', decimal =',')

# Exibe as 10 primeiras linhas da sua tabela
meus_dados.head(10)

"""**UTILIZANDO O PROMPT COM O MÉTODO DO PROTOCOLO DATACONNECT **

1.   CONTEXTO
2.   ESQUEMA DOS DADOS
3.   TAREFA
4.   CRITERIO DE ACEITE
5.   FORMATO DA RESPOSTA

1. Sou estudante de analista de dados e meu professor é alguem que quero impressionar e vou seguir o método que ele deixou no material da aula. No meu curso de analise de dados com IA, foi passado o desafio de trazer fazer algumas movimentações na tabela para a visualização. Como mostrar as 10 primeiras linhas, etc. Para isso ele fez uma data frame de dados ficcticio para o inicio da atividade.
2. Estou trabalhando no ambiente jupiter/google colab com os dados puxados diretamente do drive das minhas pastas pessoais, esse e o endereço ''/content/drive/MyDrive/dataia/dc_onboarding.csv''' la tem outras 2 arquivos que tambem preciso trabalhar com os nomes ''dc_treino_clientes.csv'' ''dc_treino_satisfacao.csv''.  Vamos focar nessa primeira tabela com 6 colunas '' projetoclienteservicohorasdata_inicionps'' eu fico em duvida sobre o que seria ''nps'' mas enfim, voce deve fazer um codigo em que a coluna ''horas'' seja convertida para outro formato, algum formato padrao, considerando que as colunas estao preenchidas pelo formato ''total'' de horas sendo ''39.8'' ''45.2'' etc. tava pensando tambem que voce deveria fazer um ranking de classificação dos clientes mais frequentes na coluna ''cliente'' e repita o mesmo procedimento na coluna serviço, ranqueando quais serviços mais frequentes, agrupe tambem os frequentes da coluna ''data_inicio'' quero ver se da pra ler algum padrao nesses meses

3. eu quero que voce me retorne um codigo executavel em phyton utilizando as bibliotecas pertinentes, por exemplo seabord, pandas, alguma biblioteca de graficos. quero que tenha um grafico representado por cada coluna que foi solicitada a soma das frequencias.
4. apenas vai estar correto o retorno em formato de codigo phyton com as bibliotecas pertinentes para a linguagem obedecendo os comandos anteriores
5. o codigo precisa ser todo comentado passo a passo de forma didatica para aprendizado em analise de dados e inteligencia artificial
"""

# ==============================================================================
# PROJETO DE ANÁLISE DE DADOS - ETAPA 1: ONBOARDING
# Autor(a): Vitória Barbosa
# Ferramentas: Python, Pandas, Matplotlib, Seaborn
# ==============================================================================

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Configuração visual dos gráficos (estilo limpo e profissional)
sns.set_theme(style="whitegrid")
plt.rcParams["font.sans-serif"] = "DejaVu Sans"

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO E INSPEÇÃO INICIAL DOS DADOS
# ------------------------------------------------------------------------------
# O parâmetro decimal=',' garante que o Python leia corretamente os números com vírgula.
caminho_arquivo = "/content/drive/MyDrive/dataia/dc_onboarding.csv"
meus_dados = pd.read_csv(caminho_arquivo, decimal=",")

# Exibe as 10 primeiras linhas solicitadas
print("--- PRIMEIRAS 10 LINHAS DO DATAFRAME ---")
display(meus_dados.head(10))

# ------------------------------------------------------------------------------
# 2. TRATAMENTO E CONVERSÃO DE TIPOS DE DADOS
# ------------------------------------------------------------------------------
# a) Coluna 'horas': Garantimos a conversão para float64 (padrão numérico contínuo)
meus_dados["horas"] = pd.to_numeric(meus_dados["horas"], errors="coerce")

# b) Coluna 'data_inicio': Convertemos texto para o formato nativo de data (Datetime)
meus_dados["data_inicio"] = pd.to_datetime(meus_dados["data_inicio"])

# c) Nota sobre NPS (Net Promoter Score):
# NPS é a métrica de satisfação do cliente (0 a 10).
# Convertemos para numérico mantendo valores nulos (NaN) intactos para não distorcer médias.
meus_dados["nps"] = pd.to_numeric(meus_dados["nps"], errors="coerce")

print("\n--- TIPOS DE DADOS APÓS TRATAMENTO ---")
print(meus_dados.dtypes)

# ------------------------------------------------------------------------------
# 3. ANÁLISES E RANKINGS DE FREQUÊNCIA
# ------------------------------------------------------------------------------

# Ranking 1: Clientes mais frequentes
ranking_clientes = (
    meus_dados["cliente"]
    .value_counts()
    .reset_index(name="quantidade")
    .rename(columns={"index": "cliente"})
)

# Ranking 2: Serviços mais frequentes
ranking_servicos = (
    meus_dados["servico"]
    .value_counts()
    .reset_index(name="quantidade")
    .rename(columns={"index": "servico"})
)

# Ranking 3: Distribuição temporal por mês
# Criamos uma coluna auxiliar de Ano-Mês (AAMM) para agrupar as demandas no tempo
meus_dados["ano_mes"] = meus_dados["data_inicio"].dt.to_period("M")
frequencia_mensal = (
    meus_dados["ano_mes"]
    .value_counts()
    .sort_index()
    .reset_index(name="quantidade")
)
frequencia_mensal["ano_mes_str"] = frequencia_mensal["ano_mes"].astype(str)

print("\n--- RANKING DE CLIENTES ---")
print(ranking_clientes)

print("\n--- RANKING DE SERVIÇOS ---")
print(ranking_servicos)

print("\n--- DISTRIBUIÇÃO MENSAL DE PROJETOS ---")
print(frequencia_mensal[["ano_mes_str", "quantidade"]])

# ------------------------------------------------------------------------------
# 4. VISUALIZAÇÃO GRÁFICA DOS RESULTADOS
# ------------------------------------------------------------------------------
# Criamos uma figura com 3 subgráficos para apresentar de forma clara e profissional
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle(
    "Análise de Frequência - Onboarding de Projetos",
    fontsize=16,
    fontweight="bold",
    y=1.05,
)

# Gráfico 1: Frequência por Cliente
sns.barplot(
    data=ranking_clientes,
    x="quantidade",
    y="cliente",
    ax=axes[0],
    palette="Blues_r",
)
axes[0].set_title("Clientes Mais Frequentes", fontsize=12, pad=10)
axes[0].set_xlabel("Quantidade de Projetos")
axes[0].set_ylabel("Cliente")

# Gráfico 2: Frequência por Serviço
sns.barplot(
    data=ranking_servicos,
    x="quantidade",
    y="servico",
    ax=axes[1],
    palette="Greens_r",
)
axes[1].set_title("Serviços Mais Solicitados", fontsize=12, pad=10)
axes[1].set_xlabel("Quantidade de Projetos")
axes[1].set_ylabel("Tipo de Serviço")

# Gráfico 3: Distribuição por Mês de Início
sns.barplot(
    data=frequencia_mensal,
    x="ano_mes_str",
    y="quantidade",
    ax=axes[2],
    palette="Oranges_r",
)
axes[2].set_title("Evolução Mensal do Início de Projetos", fontsize=12, pad=10)
axes[2].set_xlabel("Mês (Ano-Mês)")
axes[2].set_ylabel("Projetos Iniciados")
axes[2].tick_params(axis="x", rotation=45)

# Ajuste fino de layout
plt.tight_layout()
plt.show()

"""Sou estudante de Análise de Dados e estou desenvolvendo uma entrega no Google Colab para impressionar meu professor.


1. Caminho do arquivo: /content/drive/MyDrive/dataia/dc_treino_clientes.csv
Colunas presentes:  cliente_id, nome setor, contrato_mensal, desde
2. 3.  
Entao antes eu pedi um codigo que me gerasse mapas agora eu quero somente uma nova tabela com os dados limpos, quero colocar a coluna ''nome'' em ordem alfabetica, e ''setor'' tambem, a data esta como ''2022-10-01'' quero que coloque no formato ''mês/ano'' converta a coluna ''contrato mensal'' para aparecer o formato em reais e tb e altere o nome da coluna de ''contrato_mensal'' para ''valores mensal''

4. e 5.  Retorne apenas o script executável em Python utilizando as bibliotecas pertinentes para a tarefa, com comentários extremamente didáticos passo a passo.

\
"""

meus_dados = pd.read_csv('/content/drive/MyDrive/dataia/dc_treino_clientes.csv', decimal =',')
meus_dados.head(10
)

# ==============================================================================
# PROJETO DE ANÁLISE DE DADOS - ETAPA 2: TRATAMENTO E LIMPEZA DE CLIENTES
# Autor(a): Vitória Barbosa
# Ferramentas: Python, Pandas
# ==============================================================================

import pandas as pd

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO DOS DADOS BRUTOS
# ------------------------------------------------------------------------------
# Carregamos o arquivo de clientes diretamente do Google Drive
caminho_clientes = "/content/drive/MyDrive/dataia/dc_treino_clientes.csv"
df_clientes = pd.read_csv(caminho_clientes)

# Exibe os dados originais para fins de verificação inicial
print("--- DADOS ORIGINAIS (PRIMEIRAS LINHAS) ---")
display(df_clientes.head())

# ------------------------------------------------------------------------------
# 2. LIMPEZA E ORDENAÇÃO (NOME E SETOR)
# ------------------------------------------------------------------------------
# Ordenamos a tabela primeiro pela coluna 'nome' e depois pela coluna 'setor' em ordem alfabética (A-Z)
df_limpo = df_clientes.sort_values(
    by=["nome", "setor"], ascending=[True, True]
).copy()



# ------------------------------------------------------------------------------
# 3. TRANSFORMAÇÃO DE DATA (FORMATO MÊS/ANO)
# ------------------------------------------------------------------------------
# Converte a coluna 'desde' para o tipo Datetime nativo do Pandas
df_limpo["desde"] = pd.to_datetime(df_limpo["desde"])

# Formata a data para exibir apenas Mês/Ano (ex: '10/2022')
df_limpo["desde"] = df_limpo["desde"].dt.strftime("%m/%Y")

# ------------------------------------------------------------------------------
# 4. TRATAMENTO NUMÉRICO E FORMATAÇÃO DE MOEDA (R$)
# ------------------------------------------------------------------------------
# Garantimos que os valores da coluna 'contrato_mensal' sejam numéricos (float)
df_limpo["contrato_mensal"] = pd.to_numeric(
    df_limpo["contrato_mensal"], errors="coerce"
)

# Renomeamos a coluna 'contrato_mensal' para 'valores mensal'
df_limpo = df_limpo.rename(columns={"contrato_mensal": "valores mensal"})

# Formatamos os valores numéricos no formato de moeda brasileira (R$ 0.000,00)
df_limpo["valores mensal"] = df_limpo["valores mensal"].apply(
    lambda x: f"R$ {x:,.2f}".replace(",", "X")
    .replace(".", ",")
    .replace("X", ".")
    if pd.notnull(x)
    else "R$ 0,00"
)

# ------------------------------------------------------------------------------
# 5. REINICIALIZAÇÃO DO ÍNDICE E EXIBIÇÃO DA TABELA FINAL LIMPA
# ------------------------------------------------------------------------------
# Reseta os índices da tabela após a ordenação para ficarem sequenciais (0, 1, 2...)
df_limpo = df_limpo.reset_index(drop=True)

print("\n--- TABELA FINAL TRATADA E LIMPA ---")
display(df_limpo.head(26))

# ==============================================================================
# PROJETO DE ANÁLISE DE DADOS - ETAPA 2: TRATAMENTO E LIMPEZA DE CLIENTES
# Autor(a): Vitória Barbosa
# Ferramentas: Python, Pandas
# ==============================================================================

import pandas as pd

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO DOS DADOS BRUTOS
# ------------------------------------------------------------------------------
# Carregamos o arquivo de clientes diretamente do Google Drive
caminho_clientes = "/content/drive/MyDrive/dataia/dc_treino_clientes.csv"
df_clientes = pd.read_csv(caminho_clientes)

# Exibe os dados originais para fins de verificação inicial
print("--- DADOS ORIGINAIS (PRIMEIRAS LINHAS) ---")
display(df_clientes.head())

# ------------------------------------------------------------------------------
# 2. LIMPEZA E ORDENAÇÃO (NOME E SETOR)
# ------------------------------------------------------------------------------
# Ordenamos a tabela primeiro pela coluna 'nome' e depois pela coluna 'setor' em ordem alfabética (A-Z)
df_limpo = df_clientes.sort_values(
    by=["nome", "setor"], ascending=[True, True]
).copy()

# ------------------------------------------------------------------------------
# 3. TRANSFORMAÇÃO DE DATA (FORMATO MÊS/ANO)
# ------------------------------------------------------------------------------
# Converte a coluna 'desde' para o tipo Datetime nativo do Pandas
df_limpo["desde"] = pd.to_datetime(df_limpo["desde"])

# Formata a data para exibir apenas Mês/Ano (ex: '10/2022')
df_limpo["desde"] = df_limpo["desde"].dt.strftime("%m/%Y")

# ------------------------------------------------------------------------------
# 4. TRATAMENTO NUMÉRICO E FORMATAÇÃO DE MOEDA (R$)
# ------------------------------------------------------------------------------
# Garantimos que os valores da coluna 'contrato_mensal' sejam numéricos (float)
df_limpo["contrato_mensal"] = pd.to_numeric(
    df_limpo["contrato_mensal"], errors="coerce"
)

# Renomeamos a coluna 'contrato_mensal' para 'valores mensal'
df_limpo = df_limpo.rename(columns={"contrato_mensal": "valores mensal"})

# Formatamos os valores numéricos no formato de moeda brasileira (R$ 0.000,00)
df_limpo["valores mensal"] = df_limpo["valores mensal"].apply(
    lambda x: f"R$ {x:,.2f}".replace(",", "X")
    .replace(".", ",")
    .replace("X", ".")
    if pd.notnull(x)
    else "R$ 0,00"
)

# ------------------------------------------------------------------------------
# 5. REINICIALIZAÇÃO DO ÍNDICE E EXIBIÇÃO DA TABELA FINAL LIMPA
# ------------------------------------------------------------------------------
# Reseta os índices da tabela após a ordenação para ficarem sequenciais (0, 1, 2...)
df_limpo = df_limpo.reset_index(drop=True)

print("\n--- TABELA FINAL TRATADA E LIMPA ---")
display(df_limpo.head(26))

"""O codigo veio somente com a coluna clientes em ordem alfabetica, a coluna setor ainda ficou misturada, a coluna de contratos ficou zerada, e a coluna de clientes ficou embalhada so numeros e visualmente feio"""

# ==============================================================================
# PROJETO DE ANÁLISE DE DADOS - ETAPA 2: AJUSTE DE REQUISITOS E LIMPEZA
# Autor(a): Vitória Barbosa
# Ferramentas: Python, Pandas
# ==============================================================================

import pandas as pd

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO DOS DADOS BRUTOS
# ------------------------------------------------------------------------------
caminho_clientes = "/content/drive/MyDrive/dataia/dc_treino_clientes.csv"

# O parâmetro decimal=',' garante que números com vírgula sejam lidos como float
df_clientes = pd.read_csv(caminho_clientes, decimal=",")

df_limpo = df_clientes.copy()

# ------------------------------------------------------------------------------
# 2. RENOMEAÇÃO DE COLUNAS
# ------------------------------------------------------------------------------
# Renomeia 'contrato_mensal' para 'valores mensal'
df_limpo = df_limpo.rename(columns={"contrato_mensal": "valores mensal"})

# ------------------------------------------------------------------------------
# 3. FORMATAÇÃO MONETÁRIA (FLOAT PARA R$)
# ------------------------------------------------------------------------------
# Garante que a coluna seja do tipo numérico contínuo (float)
df_limpo["valores mensal"] = pd.to_numeric(
    df_limpo["valores mensal"], errors="coerce"
)

# Transforma os números em texto formatado em Reais (ex: 1250.5 -> R$ 1.250,50)
df_limpo["valores mensal"] = df_limpo["valores mensal"].apply(
    lambda x: f"R$ {x:,.2f}".replace(",", "X")
    .replace(".", ",")
    .replace("X", ".")
    if pd.notnull(x)
    else "R$ 0,00"
)

# ------------------------------------------------------------------------------
# 4. TRANSFORMAÇÃO DE DATAS
# ------------------------------------------------------------------------------
df_limpo["desde"] = pd.to_datetime(df_limpo["desde"])
df_limpo["desde"] = df_limpo["desde"].dt.strftime("%m/%Y")

# ------------------------------------------------------------------------------
# 5. ORDENAÇÃO MÚLTIPLA (CLIENTE_ID, SETOR E NOME)
# ------------------------------------------------------------------------------
# Para ordenar por cliente_id em ordem crescente (C01, C02...), colocamos ele em primeiro!
# Em seguida, encadeamos a ordenação por setor e nome em ordem alfabética (A-Z).
df_limpo = df_limpo.sort_values(
    by=["cliente_id", "setor", "nome"], ascending=[True, True, True]
)

# REGRA DE OURO: Sempre resetar o índice após ordenar uma tabela!
df_limpo = df_limpo.reset_index(drop=True)

# ------------------------------------------------------------------------------
# 6. EXIBIÇÃO DA TABELA FINAL
# ------------------------------------------------------------------------------
print("--- TABELA LIMPA E ORDENADA POR CLIENTE_ID ---")
display(df_limpo.head(15))

# ==============================================================================
# STORYTELLING COM DADOS INTERATIVO: PLOTLY LOLLIPOP CHART
# Autor(a): Vitória Barbosa
# Ferramentas: Python, Pandas, Plotly
# ==============================================================================

import pandas as pd
import plotly.graph_objects as go

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO E TRATAMENTO DOS DADOS
# ------------------------------------------------------------------------------
caminho_clientes = "/content/drive/MyDrive/dataia/dc_treino_clientes.csv"
df_clientes = pd.read_csv(caminho_clientes, decimal=",")

df_clientes["desde_dt"] = pd.to_datetime(df_clientes["desde"])
df_clientes["marca_unificada"] = df_clientes["nome"].str.split().str[0]

# Agrupa pela menor data e ordena do mais antigo para o mais recente
antiguidade = (
    df_clientes.groupby("marca_unificada")["desde_dt"]
    .min()
    .reset_index()
    .sort_values(by="desde_dt", ascending=True)
)

antiguidade["mes_ano"] = antiguidade["desde_dt"].dt.strftime("%m/%Y")

# Invertemos a ordem para que o mais antigo fique no topo da tela
antiguidade = antiguidade.iloc[::-1].reset_index(drop=True)

# ------------------------------------------------------------------------------
# 2. CONSTRUÇÃO DO GRÁFICO INTERATIVO (PLOTLY)
# ------------------------------------------------------------------------------
fig = go.Figure()

# a) Adiciona as linhas horizontais cinzas (o "cabo" do lollipop)
for i, row in antiguidade.iterrows():
    fig.add_trace(
        go.Scatter(
            x=[antiguidade["desde_dt"].min(), row["desde_dt"]],
            y=[row["marca_unificada"], row["marca_unificada"]],
            mode="lines",
            line=dict(color="#D3D3D3", width=2),
            showlegend=False,
            hoverinfo="skip",  # Ignora a linha no hover para focar no ponto
        )
    )

# b) Define cores de destaque (Destaque para as marcas mais antigas: Boreal e Dunas)
cores = [
    "#4A2E65" if marca in ["Boreal", "Dunas"] else "#888888"
    for marca in antiguidade["marca_unificada"]
]

# c) Adiciona os pontos interativos na ponta de cada linha
fig.add_trace(
    go.Scatter(
        x=antiguidade["desde_dt"],
        y=antiguidade["marca_unificada"],
        mode="markers+text",
        marker=dict(color=cores, size=14),
        text=antiguidade["mes_ano"],
        textposition="middle right",
        textfont=dict(size=12, color="#333333"),
        hovertemplate="<b>Marca:</b> %{y}<br><b>Primeiro Contrato:</b> %{text}<extra></extra>",
        showlegend=False,
    )
)

# ------------------------------------------------------------------------------
# 3. ESTILIZAÇÃO MINIMALISTA (STORYTELLING COM DADOS)
# ------------------------------------------------------------------------------
fig.update_layout(
    title=dict(
        text="<b>Antiguidade de Clientes:</b> Boreal e Dunas são as parcerias mais antigas (04/2021)",
        font=dict(size=14, color="#333333"),
        x=0.0,
        y=0.95,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    xaxis=dict(
        showgrid=False,
        zeroline=False,
        showticklabels=False,  # Oculta o eixo X para evitar o ruído do formato de data
        range=[
            antiguidade["desde_dt"].min() - pd.Timedelta(days=60),
            antiguidade["desde_dt"].max() + pd.Timedelta(days=365),
        ],  # Dá espaço à direita para a caixa de texto não cortar
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        tickfont=dict(size=12, color="#333333", family="sans-serif"),
    ),
    margin=dict(l=100, r=100, t=80, b=40),
    height=450,
    width=850,
)

# Exibe o gráfico interativo no Google Colab
fig.show()

# ==============================================================================
# STORYTELLING COM DADOS: FATURAMENTO POR MARCA (PLOTLY INTERATIVO)
# Autor(a): Vitória Barbosa
# Estilo: Minimalista / Cole Nussbaumer Knaflic
# ==============================================================================

import pandas as pd
import plotly.graph_objects as go

# 1. Carregamento e Tratamento dos Dados
caminho_clientes = "/content/drive/MyDrive/dataia/dc_treino_clientes.csv"
df_clientes = pd.read_csv(caminho_clientes, decimal=",")

# Converter faturamento para numérico e extrair marca
df_clientes["contrato_mensal"] = pd.to_numeric(
    df_clientes["contrato_mensal"], errors="coerce"
)
df_clientes["marca_unificada"] = df_clientes["nome"].str.split().str[0]

# Consolidação do faturamento total por marca
faturamento = (
    df_clientes.groupby("marca_unificada")["contrato_mensal"]
    .sum()
    .reset_index(name="total_gasto")
    .sort_values(by="total_gasto", ascending=True)  # Ascending para ordem top-down
)

# Formatação monetária (R$) para os rótulos diretos
faturamento["rótulo_faturamento"] = faturamento["total_gasto"].apply(
    lambda x: f"R$ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
)

# 2. Definição de Cores com Intenção (Destaque apenas para a marca Boreal)
cores = [
    "#4A2E65" if marca == "Boreal" else "#B0BEC5"
    for marca in faturamento["marca_unificada"]
]

# 3. Construção do Gráfico de Barras no Plotly
fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=faturamento["total_gasto"],
        y=faturamento["marca_unificada"],
        orientation="h",
        marker=dict(color=cores),
        text=faturamento["rótulo_faturamento"],
        textposition="outside",
        textfont=dict(size=12, color="#333333", family="sans-serif"),
        cliponaxis=False,
        hovertemplate="<b>Marca:</b> %{y}<br><b>Faturamento Total:</b> %{text}<extra></extra>",
    )
)

# 4. Estilização Minimalista (Eliminação de Poluição Visual)
fig.update_layout(
    title=dict(
        text="<b>Faturamento por Marca:</b> Boreal lidera com mais que o dobro da segunda colocada",
        font=dict(size=14, color="#333333"),
        x=0.0,
        y=0.95,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    xaxis=dict(
        showgrid=False,
        zeroline=False,
        showticklabels=False,  # Oculta o eixo X pois os rótulos estão nas barras
        range=[0, faturamento["total_gasto"].max() * 1.25],  # Margem à direita
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        tickfont=dict(size=12, color="#333333", family="sans-serif"),
    ),
    margin=dict(l=100, r=120, t=80, b=40),
    height=450,
    width=850,
)

# Exibe o gráfico interativo no Google Colab
fig.show()

# ==============================================================================
# DASHBOARD INTERATIVO CORRIGIDO (SEM ERRO DE KEYERROR)
# Autor(a): Vitória Barbosa
# Ferramentas: Python, Pandas, Plotly
# ==============================================================================

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 1. Carregamento e Tratamento Robusto dos Dados
caminho_clientes = "/content/drive/MyDrive/dataia/dc_treino_clientes.csv"
df_clientes = pd.read_csv(caminho_clientes, decimal=",")

# Limpa espaços em branco dos nomes das colunas
df_clientes.columns = df_clientes.columns.str.strip()

# Tratamento de tipos de dados
df_clientes["contrato_mensal"] = pd.to_numeric(
    df_clientes["contrato_mensal"], errors="coerce"
)
df_clientes["desde_dt"] = pd.to_datetime(df_clientes["desde"])
df_clientes["marca_unificada"] = df_clientes["nome"].str.split().str[0]

# --- a) Métrica 1: Setores (Tratamento seguro para qualquer versão do Pandas) ---
frequencia_setor = (
    df_clientes["setor"]
    .value_counts()
    .reset_index()
)

# Garante a nomeação correta independente da versão do Pandas
frequencia_setor.columns = ["setor", "quantidade"]
frequencia_setor = frequencia_setor.sort_values(by="quantidade", ascending=True)

# --- b) Métrica 2: Faturamento por Marca ---
faturamento = (
    df_clientes.groupby("marca_unificada")["contrato_mensal"]
    .sum()
    .reset_index(name="total_gasto")
    .sort_values(by="total_gasto", ascending=True)
)
faturamento["rótulo_faturamento"] = faturamento["total_gasto"].apply(
    lambda x: f"R$ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
)

# --- c) Métrica 3: Antiguidade por Marca ---
antiguidade = (
    df_clientes.groupby("marca_unificada")["desde_dt"]
    .min()
    .reset_index()
    .sort_values(by="desde_dt", ascending=True)
)
antiguidade["mes_ano"] = antiguidade["desde_dt"].dt.strftime("%m/%Y")
antiguidade = antiguidade.iloc[::-1].reset_index(drop=True)

# 2. Criação da Grade de Subplots (1 Linha x 3 Colunas)
fig = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=(
        "<b>1. Projetos por Setor</b>",
        "<b>2. Faturamento por Marca</b>",
        "<b>3. Antiguidade de Clientes</b>",
    ),
    horizontal_spacing=0.08,
)

# --- GRÁFICO 1: SETORES ---
cores_setor = [
    "#4A2E65" if s == "Saúde" else "#B0BEC5" for s in frequencia_setor["setor"]
]

fig.add_trace(
    go.Bar(
        x=frequencia_setor["quantidade"],
        y=frequencia_setor["setor"],
        orientation="h",
        marker=dict(color=cores_setor),
        text=frequencia_setor["quantidade"],
        textposition="outside",
        hovertemplate="<b>Setor:</b> %{y}<br><b>Projetos:</b> %{x}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=1,
)

# --- GRÁFICO 2: FATURAMENTO ---
cores_fat = [
    "#4A2E65" if m == "Boreal" else "#B0BEC5"
    for m in faturamento["marca_unificada"]
]

fig.add_trace(
    go.Bar(
        x=faturamento["total_gasto"],
        y=faturamento["marca_unificada"],
        orientation="h",
        marker=dict(color=cores_fat),
        text=faturamento["rótulo_faturamento"],
        textposition="outside",
        hovertemplate="<b>Marca:</b> %{y}<br><b>Faturamento:</b> %{text}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=2,
)

# --- GRÁFICO 3: ANTIGUIDADE (LOLLIPOP) ---
for i, row in antiguidade.iterrows():
    fig.add_trace(
        go.Scatter(
            x=[antiguidade["desde_dt"].min(), row["desde_dt"]],
            y=[row["marca_unificada"], row["marca_unificada"]],
            mode="lines",
            line=dict(color="#D3D3D3", width=2),
            showlegend=False,
            hoverinfo="skip",
        ),
        row=1,
        col=3,
    )

cores_ant = [
    "#4A2E65" if m in ["Boreal", "Dunas"] else "#888888"
    for m in antiguidade["marca_unificada"]
]

fig.add_trace(
    go.Scatter(
        x=antiguidade["desde_dt"],
        y=antiguidade["marca_unificada"],
        mode="markers+text",
        marker=dict(color=cores_ant, size=12),
        text=antiguidade["mes_ano"],
        textposition="middle right",
        textfont=dict(size=10, color="#333333"),
        hovertemplate="<b>Marca:</b> %{y}<br><b>Início:</b> %{text}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=3,
)

# 3. Estilização e Layout Final
fig.update_layout(
    title=dict(
        text="<b>Visão Consolidada da Carteira de Clientes:</b> Saúde é o maior setor, enquanto Boreal lidera em receita e histórico",
        font=dict(size=15, color="#333333"),
        x=0.0,
        y=0.98,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    height=500,
    width=1350,
    margin=dict(l=80, r=80, t=90, b=40),
)

# Ajustes dos eixos
for col in [1, 2, 3]:
    fig.update_xaxes(
        showgrid=False, zeroline=False, showticklabels=False, row=1, col=col
    )
    fig.update_yaxes(
        showgrid=False,
        zeroline=False,
        tickfont=dict(size=11, color="#333333"),
        row=1,
        col=col,
    )

fig.update_xaxes(
    range=[0, frequencia_setor["quantidade"].max() * 1.25], row=1, col=1
)
fig.update_xaxes(
    range=[0, faturamento["total_gasto"].max() * 1.35], row=1, col=2
)
fig.update_xaxes(
    range=[
        antiguidade["desde_dt"].min() - pd.Timedelta(days=60),
        antiguidade["desde_dt"].max() + pd.Timedelta(days=450),
    ],
    row=1,
    col=3,
)

# Exibe o painel completo
fig.show()

# ==============================================================================
# ANÁLISE DE SATISFAÇÃO DE CLIENTES (dc_treino_satisfacao.csv)
# Autor(a): Vitória Barbosa
# Estilo: Storytelling com Dados / Minimalista
# ==============================================================================

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO E PROCESSAMENTO DOS DADOS
# ------------------------------------------------------------------------------
caminho_satisfacao = "/content/drive/MyDrive/dataia/dc_treino_satisfacao.csv"
df_sat = pd.read_csv(caminho_satisfacao, decimal=",")

# Limpeza de cabeçalhos e conversão de tipos
df_sat.columns = df_sat.columns.str.strip()
df_sat["nota"] = pd.to_numeric(df_sat["nota"], errors="coerce")
df_sat["respondeu_em_dt"] = pd.to_datetime(df_sat["respondeu_em"])

# Extração de Ano-Mês para agrupamento temporal
df_sat["ano_mes"] = df_sat["respondeu_em_dt"].dt.to_period("M").astype(str)

# --- a) Evolução Mês a Mês (Média, Mínima, Máxima e Contagem) ---
evolucao_mensal = (
    df_sat.groupby("ano_mes")
    .agg(
        nota_media=("nota", "mean"),
        qtd_respostas=("nota", "count"),
        nota_min=("nota", "min"),
        nota_max=("nota", "max"),
    )
    .reset_index()
)

# Formatação visual do mês/ano
evolucao_mensal["mes_rotulo"] = pd.to_datetime(
    evolucao_mensal["ano_mes"]
).dt.strftime("%m/%Y")

# --- b) Categorização de Frequência de Notas ---
# Classificação Padrão de Mercado (NPS/CSAT):
# Ruim: 1 a 5 | Média: 6 a 7 | Boa: 8 a 10
def classificar_nota(nota):
    if nota <= 5:
        return "Ruim (1 a 5)"
    elif nota <= 7:
        return "Média (6 a 7)"
    else:
        return "Boa (8 a 10)"


df_sat["categoria_nota"] = df_sat["nota"].apply(classificar_nota)

distribuicao = (
    df_sat["categoria_nota"]
    .value_counts()
    .reset_index()
)
distribuicao.columns = ["categoria", "frequencia"]

# Ordena explicitamente: Ruim -> Média -> Boa
ordem_cat = ["Ruim (1 a 5)", "Média (6 a 7)", "Boa (8 a 10)"]
distribuicao["categoria"] = pd.Categorical(
    distribuicao["categoria"], categories=ordem_cat, ordered=True
)
distribuicao = distribuicao.sort_values("categoria", ascending=True)

# Percentual para exibição direta
distribuicao["percentual"] = (
    distribuicao["frequencia"] / distribuicao["frequencia"].sum()
) * 100
distribuicao["rotulo"] = distribuicao.apply(
    lambda r: f"{r['frequencia']} ({r['percentual']:.1f}%)", axis=1
)

# ------------------------------------------------------------------------------
# 2. GRÁFICO 1: EVOLUÇÃO TEMPORAL DA NOTA MÉDIA (LINHA DE TENDÊNCIA)
# ------------------------------------------------------------------------------
fig_tempo = go.Figure()

# Linha principal de tendência da média
fig_tempo.add_trace(
    go.Scatter(
        x=evolucao_mensal["mes_rotulo"],
        y=evolucao_mensal["nota_media"],
        mode="lines+markers+text",
        line=dict(color="#4A2E65", width=3),
        marker=dict(size=10, color="#4A2E65"),
        text=evolucao_mensal["nota_media"].round(2),
        textposition="top center",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Mês:</b> %{x}<br><b>Média:</b> %{y:.2f}<br><b>Total Pesquisas:</b> %{customdata}<extra></extra>",
        customdata=evolucao_mensal["qtd_respostas"],
    )
)

fig_tempo.update_layout(
    title=dict(
        text="<b>Evolução da Satisfação no Tempo:</b> Nota média permaneceu alta, com variações pontuais",
        font=dict(size=14, color="#333333"),
        x=0.0,
        y=0.95,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    xaxis=dict(showgrid=False, zeroline=False, tickfont=dict(size=11)),
    yaxis=dict(
        showgrid=True,
        gridcolor="#E0E0E0",
        zeroline=False,
        range=[0, 10.5],
        title="Nota Média (0 a 10)",
    ),
    height=400,
    width=800,
    margin=dict(l=60, r=40, t=80, b=40),
)

fig_tempo.show()

# ------------------------------------------------------------------------------
# 3. GRÁFICO 2: FREQUÊNCIA DE NOTAS (RUINS, MÉDIAS, BOAS)
# ------------------------------------------------------------------------------
cores_cat = {
    "Ruim (1 a 5)": "#E53935",  # Vermelho para atenção
    "Média (6 a 7)": "#B0BEC5",  # Cinza neutro
    "Boa (8 a 10)": "#2E7D32",  # Verde para bom desempenho
}

fig_freq = go.Figure()

fig_freq.add_trace(
    go.Bar(
        x=distribuicao["frequencia"],
        y=distribuicao["categoria"],
        orientation="h",
        marker=dict(
            color=[cores_cat[cat] for cat in distribuicao["categoria"]]
        ),
        text=distribuicao["rotulo"],
        textposition="outside",
        textfont=dict(size=12, color="#333333"),
        hovertemplate="<b>Categoria:</b> %{y}<br><b>Respostas:</b> %{text}<extra></extra>",
    )
)

fig_freq.update_layout(
    title=dict(
        text="<b>Distribuição de Satisfação:</b> A grande maioria dos clientes atribuiu notas altas (8 a 10)",
        font=dict(size=14, color="#333333"),
        x=0.0,
        y=0.95,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    xaxis=dict(
        showgrid=False,
        zeroline=False,
        showticklabels=False,
        range=[0, distribuicao["frequencia"].max() * 1.25],
    ),
    yaxis=dict(showgrid=False, zeroline=False, tickfont=dict(size=12)),
    height=350,
    width=800,
    margin=dict(l=100, r=100, t=80, b=40),
)

fig_freq.show()

# ==============================================================================
# ANÁLISE DE ONBOARDING (dc_onboarding.csv)
# Autor(a): Vitória Barbosa
# Estilo: Storytelling com Dados / Minimalista
# ==============================================================================

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO E TRATAMENTO ROBUSTO DOS DADOS
# ------------------------------------------------------------------------------
caminho_onboarding = "/content/drive/MyDrive/dataia/dc_onboarding.csv"
df_onb = pd.read_csv(caminho_onboarding, decimal=",")

# Limpeza de cabeçalhos e remoção de espaços
df_onb.columns = df_onb.columns.str.strip()
df_onb["data_inicio_dt"] = pd.to_datetime(df_onb["data_inicio"])

# a) Clientes mais frequentes
clientes_freq = (
    df_onb["cliente"]
    .value_counts()
    .reset_index()
)
clientes_freq.columns = ["cliente", "quantidade"]
clientes_freq = clientes_freq.sort_values(by="quantidade", ascending=True)

# b) Serviços mais solicitados
servicos_freq = (
    df_onb["servico"]
    .value_counts()
    .reset_index()
)
servicos_freq.columns = ["servico", "quantidade"]
servicos_freq = servicos_freq.sort_values(by="quantidade", ascending=True)

# c) Evolução mensal de novos projetos
df_onb["ano_mes"] = df_onb["data_inicio_dt"].dt.to_period("M").astype(str)
evolucao_onb = (
    df_onb.groupby("ano_mes")["projeto"]
    .count()
    .reset_index(name="quantidade")
    .sort_values("ano_mes")
)
evolucao_onb["mes_rotulo"] = pd.to_datetime(
    evolucao_onb["ano_mes"]
).dt.strftime("%m/%Y")

# ------------------------------------------------------------------------------
# 2. CRIAÇÃO DO PAINEL UNIFICADO (1 LINHA x 3 COLUNAS)
# ------------------------------------------------------------------------------
fig = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=(
        "<b>1. Clientes Frequentes</b>",
        "<b>2. Serviços Solicitados</b>",
        "<b>3. Evolução de Inícios</b>",
    ),
    horizontal_spacing=0.08,
)

# --- GRÁFICO 1: CLIENTES (Destaque na AgroSerra) ---
cores_cliente = [
    "#4A2E65" if c == "AgroSerra" else "#B0BEC5" for c in clientes_freq["cliente"]
]

fig.add_trace(
    go.Bar(
        x=clientes_freq["quantidade"],
        y=clientes_freq["cliente"],
        orientation="h",
        marker=dict(color=cores_cliente),
        text=clientes_freq["quantidade"],
        textposition="outside",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Cliente:</b> %{y}<br><b>Projetos:</b> %{x}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=1,
)

# --- GRÁFICO 2: SERVIÇOS (Destaque em BI e Dashboards) ---
cores_servico = [
    "#4A2E65" if s in ["BI", "Dashboards"] else "#B0BEC5"
    for s in servicos_freq["servico"]
]

fig.add_trace(
    go.Bar(
        x=servicos_freq["quantidade"],
        y=servicos_freq["servico"],
        orientation="h",
        marker=dict(color=cores_servico),
        text=servicos_freq["quantidade"],
        textposition="outside",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Serviço:</b> %{y}<br><b>Demandas:</b> %{x}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=2,
)

# --- GRÁFICO 3: EVOLUÇÃO TEMPORAL (LINHA COM MARCADORES) ---
fig.add_trace(
    go.Scatter(
        x=evolucao_onb["mes_rotulo"],
        y=evolucao_onb["quantidade"],
        mode="lines+markers+text",
        line=dict(color="#4A2E65", width=3),
        marker=dict(size=9, color="#4A2E65"),
        text=evolucao_onb["quantidade"],
        textposition="top center",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Mês:</b> %{x}<br><b>Novos Projetos:</b> %{y}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=3,
)

# ------------------------------------------------------------------------------
# 3. AJUSTES DE LAYOUT E ELIMINAÇÃO DE POLUIÇÃO VISUAL
# ------------------------------------------------------------------------------
fig.update_layout(
    title=dict(
        text="<b>Análise de Onboarding:</b> AgroSerra lidera demandas de BI/Dashboards com recuperação de inícios a partir de Abril",
        font=dict(size=15, color="#333333"),
        x=0.0,
        y=0.98,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    height=480,
    width=1350,
    margin=dict(l=80, r=80, t=90, b=40),
)

# Limpeza e alinhamento dos eixos
for col in [1, 2, 3]:
    fig.update_xaxes(
        showgrid=False, zeroline=False, showticklabels=False, row=1, col=col
    )
    fig.update_yaxes(
        showgrid=False,
        zeroline=False,
        tickfont=dict(size=11, color="#333333"),
        row=1,
        col=col,
    )

# Exceção: exibe rótulos dos meses no eixo X da linha temporal (gráfico 3)
fig.update_xaxes(showticklabels=True, row=1, col=3)

# Expansão das margens para evitar corte de rótulos
fig.update_xaxes(
    range=[0, clientes_freq["quantidade"].max() * 1.25], row=1, col=1
)
fig.update_xaxes(
    range=[0, servicos_freq["quantidade"].max() * 1.25], row=1, col=2
)
fig.update_yaxes(
    range=[0, evolucao_onb["quantidade"].max() * 1.25], row=1, col=3
)

# Exibe o painel interativo limpo
fig.show()

# ==============================================================================
# PAINEL DE ONBOARDING REFINADO (AJUSTE DE ESPESSURA, GRID E RÓTULOS)
# Autor(a): Vitória Barbosa
# Estilo: Storytelling com Dados / Minimalista
# ==============================================================================

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ------------------------------------------------------------------------------
# 1. CARREGAMENTO E TRATAMENTO DOS DADOS
# ------------------------------------------------------------------------------
caminho_onboarding = "/content/drive/MyDrive/dataia/dc_onboarding.csv"
df_onb = pd.read_csv(caminho_onboarding, decimal=",")

# Limpeza e conversão
df_onb.columns = df_onb.columns.str.strip()
df_onb["data_inicio_dt"] = pd.to_datetime(df_onb["data_inicio"])

# a) Clientes frequentes
clientes_freq = df_onb["cliente"].value_counts().reset_index()
clientes_freq.columns = ["cliente", "quantidade"]
clientes_freq = clientes_freq.sort_values(by="quantidade", ascending=True)

# b) Serviços solicitados
servicos_freq = df_onb["servico"].value_counts().reset_index()
servicos_freq.columns = ["servico", "quantidade"]
servicos_freq = servicos_freq.sort_values(by="quantidade", ascending=True)

# c) Evolução temporal
df_onb["ano_mes"] = df_onb["data_inicio_dt"].dt.to_period("M").astype(str)
evolucao_onb = (
    df_onb.groupby("ano_mes")["projeto"]
    .count()
    .reset_index(name="quantidade")
    .sort_values("ano_mes")
)
evolucao_onb["mes_rotulo"] = pd.to_datetime(
    evolucao_onb["ano_mes"]
).dt.strftime("%b/%Y")

# ------------------------------------------------------------------------------
# 2. CRIAÇÃO DA GRADE DE SUBPLOTS
# ------------------------------------------------------------------------------
fig = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=(
        "<b>1. Clientes Frequentes</b>",
        "<b>2. Serviços Solicitados</b>",
        "<b>3. Evolução de Inícios</b>",
    ),
    horizontal_spacing=0.10,
)

# --- GRÁFICO 1: CLIENTES ---
cores_cliente = [
    "#4A2E65" if c == "AgroSerra" else "#B0BEC5" for c in clientes_freq["cliente"]
]

fig.add_trace(
    go.Bar(
        x=clientes_freq["quantidade"],
        y=clientes_freq["cliente"],
        orientation="h",
        marker=dict(color=cores_cliente),
        text=clientes_freq["quantidade"],
        textposition="outside",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Cliente:</b> %{y}<br><b>Projetos:</b> %{x}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=1,
)

# --- GRÁFICO 2: SERVIÇOS (Barras mais finas e elegantes) ---
cores_servico = [
    "#4A2E65" if s in ["BI", "Dashboards"] else "#B0BEC5"
    for s in servicos_freq["servico"]
]

fig.add_trace(
    go.Bar(
        x=servicos_freq["quantidade"],
        y=servicos_freq["servico"],
        orientation="h",
        marker=dict(color=cores_servico),
        text=servicos_freq["quantidade"],
        textposition="outside",
        textfont=dict(size=11, color="#333333"),
        width=0.45,  # Reduz a largura das barras para evitar o aspecto 'grosso'
        hovertemplate="<b>Serviço:</b> %{y}<br><b>Demandas:</b> %{x}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=2,
)

# --- GRÁFICO 3: EVOLUÇÃO TEMPORAL (Linha mais refinada + Grid de fundo) ---
fig.add_trace(
    go.Scatter(
        x=evolucao_onb["mes_rotulo"],
        y=evolucao_onb["quantidade"],
        mode="lines+markers+text",
        line=dict(color="#4A2E65", width=2.5),  # Espessura moderada
        marker=dict(size=8, color="#4A2E65"),
        text=evolucao_onb["quantidade"],
        textposition="top center",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Mês:</b> %{x}<br><b>Projetos Iniciados:</b> %{y}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=3,
)

# ------------------------------------------------------------------------------
# 3. ESTILIZAÇÃO E GRID DE APOIO
# ------------------------------------------------------------------------------
fig.update_layout(
    title=dict(
        text="<b>Análise de Onboarding:</b> AgroSerra lidera demandas de BI/Dashboards com recuperação de inícios a partir de Abril",
        font=dict(size=15, color="#333333"),
        x=0.0,
        y=0.98,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    height=480,
    width=1350,
    margin=dict(l=80, r=80, t=90, b=60),
    bargap=0.3,  # Espaçamento entre as barras
)

# Configurações gerais dos eixos 1 e 2 (sem poluição)
for col in [1, 2]:
    fig.update_xaxes(
        showgrid=False, zeroline=False, showticklabels=False, row=1, col=col
    )
    fig.update_yaxes(
        showgrid=False,
        zeroline=False,
        tickfont=dict(size=11, color="#333333"),
        row=1,
        col=col,
    )

# Configurações específicas do Gráfico 3 (Evolução de Inícios)
fig.update_xaxes(
    title_text="<b>Mês de Início</b>",
    title_font=dict(size=11, color="#555555"),
    showticklabels=True,
    showgrid=True,
    gridcolor="#F0F0F0",  # Grid sutil para ancorar os pontos
    zeroline=False,
    tickfont=dict(size=10, color="#333333"),
    row=1,
    col=3,
)

fig.update_yaxes(
    title_text="<b>Novos Projetos</b>",
    title_font=dict(size=11, color="#555555"),
    showticklabels=True,
    showgrid=True,
    gridcolor="#F0F0F0",  # Grid sutil no eixo Y
    zeroline=False,
    tickfont=dict(size=10, color="#333333"),
    row=1,
    col=3,
)

# Margens dos eixos para evitar cortes
fig.update_xaxes(
    range=[0, clientes_freq["quantidade"].max() * 1.25], row=1, col=1
)
fig.update_xaxes(
    range=[0, servicos_freq["quantidade"].max() * 1.25], row=1, col=2
)
fig.update_yaxes(
    range=[0, evolucao_onb["quantidade"].max() * 1.25], row=1, col=3
)

# Exibe o painel ajustado
fig.show()

# ==============================================================================
# PAINEL DE ONBOARDING - REFINADO COM CLEVELAND DOT PLOT
# Autor(a): Vitória Barbosa
# Estilo: Storytelling com Dados / Minimalista
# ==============================================================================

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 1. Carregamento e Tratamento dos Dados
caminho_onboarding = "/content/drive/MyDrive/dataia/dc_onboarding.csv"
df_onb = pd.read_csv(caminho_onboarding, decimal=",")

df_onb.columns = df_onb.columns.str.strip()
df_onb["data_inicio_dt"] = pd.to_datetime(df_onb["data_inicio"])

# a) Clientes Frequentes
clientes_freq = df_onb["cliente"].value_counts().reset_index()
clientes_freq.columns = ["cliente", "quantidade"]
clientes_freq = clientes_freq.sort_values(by="quantidade", ascending=True)

# b) Serviços Solicitados
servicos_freq = df_onb["servico"].value_counts().reset_index()
servicos_freq.columns = ["servico", "quantidade"]
servicos_freq = servicos_freq.sort_values(by="quantidade", ascending=True)

# c) Evolução Temporal
df_onb["ano_mes"] = df_onb["data_inicio_dt"].dt.to_period("M").astype(str)
evolucao_onb = (
    df_onb.groupby("ano_mes")["projeto"]
    .count()
    .reset_index(name="quantidade")
    .sort_values("ano_mes")
)
evolucao_onb["mes_rotulo"] = pd.to_datetime(
    evolucao_onb["ano_mes"]
).dt.strftime("%b/%Y")

# 2. Criação da Grade de Subplots
fig = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=(
        "<b>1. Clientes Frequentes</b>",
        "<b>2. Distribuição por Serviço</b>",
        "<b>3. Evolução de Inícios</b>",
    ),
    horizontal_spacing=0.10,
)

# --- GRÁFICO 1: CLIENTES ---
cores_cliente = [
    "#4A2E65" if c == "AgroSerra" else "#B0BEC5" for c in clientes_freq["cliente"]
]

fig.add_trace(
    go.Bar(
        x=clientes_freq["quantidade"],
        y=clientes_freq["cliente"],
        orientation="h",
        marker=dict(color=cores_cliente),
        text=clientes_freq["quantidade"],
        textposition="outside",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Cliente:</b> %{y}<br><b>Projetos:</b> %{x}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=1,
)

# --- GRÁFICO 2: SERVIÇOS (Cleveland Dot Plot - Leve e Elegante) ---
# Adiciona linhas guias sutis
for _, row in servicos_freq.iterrows():
    fig.add_trace(
        go.Scatter(
            x=[0, row["quantidade"]],
            y=[row["servico"], row["servico"]],
            mode="lines",
            line=dict(color="#E0E0E0", width=1.5, dash="dot"),
            showlegend=False,
            hoverinfo="skip",
        ),
        row=1,
        col=2,
    )

cores_dot = [
    "#4A2E65" if s in ["BI", "Dashboards"] else "#78909C"
    for s in servicos_freq["servico"]
]

fig.add_trace(
    go.Scatter(
        x=servicos_freq["quantidade"],
        y=servicos_freq["servico"],
        mode="markers+text",
        marker=dict(color=cores_dot, size=12),
        text=servicos_freq["quantidade"],
        textposition="middle right",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Serviço:</b> %{y}<br><b>Projetos:</b> %{x}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=2,
)

# --- GRÁFICO 3: EVOLUÇÃO TEMPORAL ---
fig.add_trace(
    go.Scatter(
        x=evolucao_onb["mes_rotulo"],
        y=evolucao_onb["quantidade"],
        mode="lines+markers+text",
        line=dict(color="#4A2E65", width=2.5),
        marker=dict(size=8, color="#4A2E65"),
        text=evolucao_onb["quantidade"],
        textposition="top center",
        textfont=dict(size=11, color="#333333"),
        hovertemplate="<b>Mês:</b> %{x}<br><b>Inícios:</b> %{y}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=3,
)

# 3. Estilização e Layout Final
fig.update_layout(
    title=dict(
        text="<b>Análise de Onboarding:</b> Demandas equilibradas entre serviços, lideradas por AgroSerra e com alta em Abril",
        font=dict(size=15, color="#333333"),
        x=0.0,
        y=0.98,
    ),
    plot_bgcolor="white",
    paper_bgcolor="white",
    height=480,
    width=1350,
    margin=dict(l=80, r=80, t=90, b=60),
)

# Eixos 1 (Clientes)
fig.update_xaxes(
    showgrid=False,
    zeroline=False,
    showticklabels=False,
    range=[0, clientes_freq["quantidade"].max() * 1.25],
    row=1,
    col=1,
)
fig.update_yaxes(
    showgrid=False,
    zeroline=False,
    tickfont=dict(size=11, color="#333333"),
    row=1,
    col=1,
)

# Eixos 2 (Serviços - Dot Plot)
fig.update_xaxes(
    title_text="<b>Demandas</b>",
    title_font=dict(size=11, color="#555555"),
    showticklabels=True,
    showgrid=True,
    gridcolor="#F0F0F0",
    range=[0, 10],
    row=1,
    col=2,
)
fig.update_yaxes(
    showgrid=False,
    zeroline=False,
    tickfont=dict(size=11, color="#333333"),
    row=1,
    col=2,
)

# Eixos 3 (Evolução)
fig.update_xaxes(
    title_text="<b>Mês de Início</b>",
    title_font=dict(size=11, color="#555555"),
    showticklabels=True,
    showgrid=True,
    gridcolor="#F0F0F0",
    row=1,
    col=3,
)
fig.update_yaxes(
    title_text="<b>Novos Projetos</b>",
    title_font=dict(size=11, color="#555555"),
    showticklabels=True,
    showgrid=True,
    gridcolor="#F0F0F0",
    range=[0, evolucao_onb["quantidade"].max() * 1.25],
    row=1,
    col=3,
)

fig.show()

"""**Nessa parte eu quis realizar uma apresentação dos dados em formato de apresentação seguindo algumas recomendações do livro ''StoryTelling com Dados"**"""

import glob
import os
import re
from IPython.display import Image, display

# 1. Busca todas as imagens PNG
imagens = glob.glob("/content/drive/MyDrive/dataia/slides/*.png")


# 2. O QUE FOI FEITO PARA CORRIGIR:
# Criamos uma função chave que extrai o número do nome do arquivo
def extrair_numero(caminho):
    nome = os.path.basename(caminho)
    numeros = re.findall(
        r"\d+", nome
    )  # Procura por sequências de dígitos (ex: '10' em 'slide10.png')
    return (
        int(numeros[0]) if numeros else 0
    )  # Converte o texto '10' para o número 10


# 3. Ordenamos usando a chave numérica personalizada
imagens_ordenadas = sorted(imagens, key=extrair_numero)

# 4. Exibição na ordem numérica correta (1, 2, 3... 10)
for img in imagens_ordenadas:
    print(f"\nExibindo: {os.path.basename(img)}")
    display(Image(filename=img, width=800))

from IPython.display import HTML, display

link_canva = "https://canva.link/gzvvd9rztcsom9k/view"

html_canva = f"""
<div style="background-color: #F3E5F5; border: 1px solid #4A2E65; padding: 15px; border-radius: 8px; text-align: center;">
    <p style="color: #4A2E65; font-weight: bold; margin-bottom: 10px;">✨ Para navegação interativa com máxima resolução e links ativos:</p>
    <a href="{link_canva}" target="_blank" style="background-color: #4A2E65; color: white; padding: 10px 24px; text-decoration: none; border-radius: 20px; font-weight: bold;">
        🚀 Visualizar Apresentação Interativa no Canva
    </a>
</div>
"""
display(HTML(html_canva))